version: '2.0'
services:
  hadoop-master:
    container_name: hadoop-master-container
    hostname: hadoop-master
    image: testing/hdp3.1-hive
    environment:
      - AWS_ACCESS_KEY_ID=testing
      - AWS_SECRET_ACCESS_KEY=testing
    ports:
      - "10000:10000"
  moto-server:
    container_name: moto-server-container
    hostname: moto-server
    image: motoserver/moto
    ports:
      - "5000:5000"
  presto:
    container_name: presto-container
    hostname: presto
    image: prestosql-docker
    environment:
      - AWS_ACCESS_KEY_ID=testing
      - AWS_SECRET_ACCESS_KEY=testing
    ports:
      - "8080:8080"
